##### version 1
#FROM fabric8/java-jboss-openjdk8-jdk
#ARG JAVA_WITH_DEPS
#ADD /${JAVA_WITH_DEPS} app.jar
##EXPOSE 8080
#ENTRYPOINT ["java","-jar","app.jar"]

##### version 2
#FROM openjdk:8-jdk-alpine
#ARG JAVA_WITH_DEPS
#ADD /${JAVA_WITH_DEPS} app.jar
##EXPOSE 8080
#ENTRYPOINT ["java","-jar","app.jar"]

##### version 3
#FROM gcr.io/distroless/java
#ARG JAVA_WITH_DEPS
#ADD /${JAVA_WITH_DEPS} app.jar
##EXPOSE 8080
#ENTRYPOINT ["java","-jar","app.jar"]
